#!/usr/bin/env python3
"""Generate schema-derived Mermaid, ERD PDF and PNG (reportlab + pymupdf).

The diagrams show primary/foreign keys and selected state/value columns, not
every column. The SQL remains authoritative for defaults/checks/indexes/triggers.
"""
from pathlib import Path
import re

import pymupdf
from reportlab.pdfgen import canvas
from reportlab.lib.colors import HexColor, Color, white

ROOT = Path(__file__).resolve().parents[1]


def schema():
    text = re.sub(r"--[^\n]*", "", (ROOT / "db/finalized-schema.sql").read_text(encoding="utf-8"))
    tables, relations = {}, []
    for match in re.finditer(r"CREATE TABLE (\w+)\s*\((.*?)\n\);", text, re.S):
        name, body = match.groups()
        columns = []
        primary = set(re.findall(r"^\s*(\w+)\s+[^\n,]*PRIMARY KEY", body, re.M))
        for keys in re.findall(r"PRIMARY KEY\s*\(([^)]+)\)", body):
            primary.update(key.strip() for key in keys.split(","))
        foreign = {}
        for keys, parent, targets in re.findall(r"FOREIGN KEY\s*\(([^)]+)\)\s*REFERENCES\s+(\w+)\s*\(([^)]+)\)", body):
            for key, target in zip(keys.split(","), targets.split(",")):
                foreign[key.strip()] = (parent, target.strip())
                relations.append((name, key.strip(), parent, target.strip()))
        for line in body.splitlines():
            column = re.match(r"\s*(\w+)\s+(UUID|VARCHAR\(\d+\)|TEXT|BOOLEAN|BIGINT|INTEGER|INT|NUMERIC\([^)]+\)|TIMESTAMPTZ|DATE|JSONB|BYTEA)", line, re.I)
            if column:
                col, kind = column.groups()
                columns.append((col, kind, col in primary, foreign.get(col)))
        tables[name] = columns
    assert len(tables) == 18, f"Review schema groups when table count changes: {len(tables)}"
    return tables, relations


def main():
    tables, relations = schema()
    mermaid = ["# Current database ERD", "", "Generated by `python scripts/generate_erd.py` from `db/finalized-schema.sql`.", "", "```mermaid", "erDiagram"]
    for table, columns in tables.items():
        mermaid.append(f"  {table} {{")
        for name, kind, pk, fk in columns:
            flags = ",".join(flag for flag, present in (("PK", pk), ("FK", fk)) if present)
            mermaid.append(f"    {re.sub('[^A-Za-z]', '', kind).lower()} {name}" + (f" {flags}" if flags else ""))
        mermaid.append("  }")
    for child, key, parent, target in relations:
        # Optionality differs by column; the PDF explicitly uses FK arrows only.
        mermaid.append(f'  {parent} |o--o{{ {child} : "{key}"')
    mermaid.extend(["```", "", "FK arrows identify references. Nullability, unique constraints and deletion behavior are defined in the SQL."])
    (ROOT / "db/er-diagram.md").write_text("\n".join(mermaid)+"\n", encoding="utf-8")
    groups = [
        ("Identity and accounts", ["users", "customer_profiles", "financial_profiles", "analyst_profiles", "sessions", "password_reset_tokens", "accounts"]),
        ("Trading and quote contracts", ["accounts", "instruments", "quotes", "orders", "fills", "order_status_history", "cash_holds"]),
        ("Settlement and audit", ["users", "accounts", "instruments", "fills", "holdings", "holding_movements", "cash_balances", "cash_transactions", "audit_log"]),
    ]
    width, height = 1440, 1020
    pdf = canvas.Canvas(str(ROOT / "db/ER_Diagram.pdf"), pagesize=(width, height), invariant=1)
    pdf.setTitle("NextTrade current schema - entity relationships")
    selected = {"status", "account_status", "trading_enabled", "balance", "settled_balance", "unsettled_balance", "amount", "quantity", "avg_cost", "side", "execution_attempts", "quoted_at", "bid", "ask", "source", "symbol", "user_role", "event_type", "settlement_status", "hold_status"}
    for page, (title, names) in enumerate(groups, 1):
        pdf.setFillColor(HexColor("#122D45")); pdf.setFont("Helvetica-Bold", 25)
        pdf.drawString(45, height-52, f"NextTrade / {title}")
        pdf.setFont("Helvetica", 12); pdf.drawString(45, height-76, "Current schema key/state view. Each FK lists its referenced table; arrows point from child to parent.")
        positions = {}
        for index, name in enumerate(names):
            col, row = index % 3, index // 3
            positions[name] = (45+col*475, height-135-row*285, 400, 220)
        # Draw relationship lines behind cards, with distinct bends per relation.
        for index, (child, key, parent, target) in enumerate(relations):
            if child not in positions or parent not in positions:
                continue
            x1,y1,w1,h1=positions[child]; x2,y2,w2,h2=positions[parent]
            x1+=w1/2; y1-=h1/2; x2+=w2/2; y2-=h2/2
            pdf.setStrokeColor(Color(.23,.48,.66,alpha=.45));pdf.setLineWidth(1.2)
            pdf.line(x1,y1,x2,y2)
        for name,(x,y,w,h) in positions.items():
            pdf.setFillColor(white); pdf.setStrokeColor(HexColor("#A7BDCD"));pdf.roundRect(x,y-h,w,h,7,fill=1,stroke=1)
            pdf.setFillColor(HexColor("#153F5D"));pdf.roundRect(x,y-33,w,33,7,fill=1,stroke=0)
            pdf.setFillColor(white);pdf.setFont("Helvetica-Bold",14);pdf.drawString(x+12,y-22,name)
            rows = [(n,k,pk,fk) for n,k,pk,fk in tables[name] if pk or fk or n in selected]
            assert len(rows) <= 11, (name, len(rows))
            for row,(n,k,pk,fk) in enumerate(rows):
                text = ("PK " if pk else "") + n + (f" -> {fk[0]}.{fk[1]}" if fk else "")
                pdf.setFillColor(HexColor("#153F5D") if fk else HexColor("#233545"));pdf.setFont("Helvetica",10)
                assert pdf.stringWidth(text,"Helvetica",10)<w-24,text
                pdf.drawString(x+12,y-53-row*14,text)
        pdf.setFillColor(HexColor("#476171"));pdf.setFont("Helvetica",11)
        pdf.drawString(45,40,"Source: db/finalized-schema.sql | Regenerate: python scripts/generate_erd.py | All columns: db/er-diagram.md")
        pdf.drawRightString(width-45,40,f"{page} / {len(groups)}")
        pdf.showPage()
    pdf.save()
    document = pymupdf.open(ROOT / "db/ER_Diagram.pdf")
    # All pages in one PNG, preserving the required legacy link and all entities.
    pixmaps = [page.get_pixmap(matrix=pymupdf.Matrix(1,1), alpha=False) for page in document]
    from PIL import Image
    result = Image.new("RGB", (width, height*len(pixmaps)), "white")
    for index,pixmap in enumerate(pixmaps):
        result.paste(Image.frombytes("RGB", (pixmap.width,pixmap.height),pixmap.samples),(0,index*height))
    result.save(ROOT / "db/er_diagram.png")
    print(f"Generated 18 entities, {len(relations)} foreign keys, {len(groups)} PDF pages and combined PNG")


if __name__ == "__main__":
    main()
